alias audio='inxi -A'
alias cd..='cd ..'
alias clean='clear; seq 1 80 | sort -R | sparklines | lolcat'
alias depends=function_depends
alias df='df -h'
alias edit=gnome-text-editor
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias free='free -mt'
alias graphics='inxi -G'
alias grep='grep --color=auto'
alias grh='git reset --hard'
alias grub-update='sudo grub-mkconfig -o /boot/grub/grub.cfg'
alias kernel='ls /usr/lib/modules'
alias kernels='ls /usr/lib/modules'
alias l=ls
alias l.='ls -A | egrep '\''^\.'\'
alias la='ls -a'
alias listdir='ls -d */ > list'
alias ll='ls -alFh'
alias ls='lsd -a --group-directories-first'
alias pdw=pwd
alias rms='rm /home/lana/Pictures/Screenshots/Screenshot*'
alias run-help=man
alias sdn='shutdown now'
alias setlocale='sudo localectl set-locale LANG=en_US.UTF-8'
alias sysfailed='systemctl list-units --failed'
alias tobash='sudo chsh lana -s /bin/bash && echo '\''Now log out.'\'
alias tofish='sudo chsh lana -s /bin/fish && echo '\''Now log out.'\'
alias tozsh='sudo chsh lana -s /bin/zsh && echo '\''Now log out.'\'
alias unhblock='hblock -S none -D none'
alias update-grub='sudo grub-mkconfig -o /boot/grub/grub.cfg'
alias userlist='cut -d: -f1 /etc/passwd | sort'
alias wget='wget -c'
alias which='alias | /usr/bin/which --tty-only --read-alias --show-tilde --show-dot'
alias which-command=whence
alias xzegrep='xzegrep --color=auto'
alias xzfgrep='xzfgrep --color=auto'
alias xzgrep='xzgrep --color=auto'
alias yta-aac='yt-dlp --extract-audio --audio-format aac '
alias yta-best='yt-dlp --extract-audio --audio-format best '
alias yta-flac='yt-dlp --extract-audio --audio-format flac '
alias yta-mp3='yt-dlp --extract-audio --audio-format mp3 '
alias ytv-best='yt-dlp -f '\''bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio'\'' --merge-output-format mkv '
alias zegrep='zegrep --color=auto'
alias zfgrep='zfgrep --color=auto'
alias zgrep='zgrep --color=auto'
alias mkdir='mkcd'
alias cat='bat'
